# Generated by Django 4.2.7 on 2023-11-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_picturefolder_main_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefolder',
            name='main_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.picturefolder'),
        ),
    ]
