# Generated by Django 4.2.7 on 2023-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_picturefolder_main_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefolder',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
