# Generated by Django 4.2.7 on 2023-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_picturefolder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturefolder',
            name='main_folder',
        ),
        migrations.AddField(
            model_name='picture',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
