# Generated by Django 4.2.7 on 2023-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_picturefolder_main_folder_picture_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.CharField(max_length=250),
        ),
    ]
