# Generated by Django 4.2.7 on 2023-12-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
